# Generated by Django 5.1.7 on 2025-03-21 12:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='userotp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
