# Generated by Django 4.2.11 on 2025-03-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userotp_created_at_userotp_expiration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
