# Generated by Django 4.2.11 on 2025-03-22 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userotp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='userimage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img1', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('img2', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('img3', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
