# Generated by Django 4.2.11 on 2025-03-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='img1',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='uuid'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='img2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='uuid'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='img3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='uuid'),
        ),
    ]
